### ISSUE TITLE
License and examples of use?

### ISSUE THREAD

**Issue by jeremyworger** [Ricardicus/wavefunc-collapse#1]
Was wondering if you could provide the input settings used for the examples you have shown [https://github.com/Ricardicus/wavefunc-collapse](url)  
Also curious about whether or not you'd add a license to this project.  
Cheers

**Comment by Ricardicus** [comment]
Hi! Sorry for the late reply! 
I added a License.

The program has a lot of arguments, one can use it in many ways. 
But, input image is given by the "-i" argument, and output with "-o".
For example, if you want to generate a flowers image using the flowers sample
from the origin repo:

```
$ python3 main.py -i samples/Flowers.png -o flowers.png -s 2 -d 100x50 --keepdown --keepup
```

(symmetry was how one could get more features from the input by mirroring it etc.)

For more details:

```
$ python3 main.py -h      
usage: main.py [-h] [-n N] [-s {1,2,3,4,5,6,7,8}] [-o OUTPUT] [-d DIMENSION] [-i INPUT] [--iscale ISCALE] [--oscale OSCALE] [--nostrip] [--keepup] [--keepdown]

Generate pixelimages

optional arguments:
  -h, --help            show this help message and exit
  -n N                  Overlapping window size (feature generator)
  -s {1,2,3,4,5,6,7,8}, --symmetry {1,2,3,4,5,6,7,8}
                        Symmetry value (1-8). 1: no symmetry, 8: all symmetries
  -o OUTPUT, --output OUTPUT
                        Output file (.png)
  -d DIMENSION, --dimension DIMENSION
                        Output dimension WidthxHeight, e.g. 80x60
  -i INPUT, --input INPUT
                        Input image, see the "samples" folder
  --iscale ISCALE       Input image scaling
  --oscale OSCALE       Output image scaling
  --nostrip             Don't strip output size to factor of nearest feature window size (N) multiple
  --keepup              Mirror upper parts of the image with the original
  --keepdown            Mirror lower parts of the image with the original
```

**Comment by jeremyworger** [comment]
Awesome! Just so I understand fully, what was the full command for the "big output space" for the flower image you have there? 
Just so I can replicate the same image.

**Comment by Ricardicus** [comment]
I dont remember 😅 but check the image size, and set the -d argument to that! Should render the same thing. I used the --keepup and --keedown arguments just to preserve the ground and sky 😊
